version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - bibman.env
    ports:
      - "5432:5432" # for development
    # environment:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_db:
